### ISSUE TITLE
Удаление даты "Открыть заново" при переводе в незамороженый статус

### ISSUE THREAD

**Issue by miramir** [centosadmin/redmine_issue_open_date#1]
Наверное правильно удалять дату "Открыть заново" при переводе в "не замороженные" статусы, если она была установлена. Эта дата смущает при просмотре задачи.

**Comment by olemskoi** [comment]
Иван, спасибо за предложение! Сделаем.


среда, 9 декабря 2015 г. пользователь Иван Багаев написал:

> Наверное правильно удалять дату "Открыть заново" при переводе в "не
> замороженные" статусы, если она была установлена. Эта дата смущает при
> просмотре задачи.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centosadmin/redmine_issue_open_date/issues/1>.
>


-- 
Олемской Игорь
Компания "Southbridge"

+7 (495) 66-55-027 доб.77
www.southbridge.ru

**Comment by arturtr** [comment]
Готово

**Comment by olemskoi** [comment]
Спасибо!



среда, 9 декабря 2015 г. пользователь Artur Trofimov написал:

> Готово
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centosadmin/redmine_issue_open_date/issues/1#issuecomment-163246458>
> .
>


-- 
Олемской Игорь
Компания "Southbridge"

+7 (495) 66-55-027 доб.77
www.southbridge.ru
