### ISSUE TITLE
NameError: uninitialized constant IssueOpenWorker

### ISSUE THREAD

**Issue by hempalex** [centosadmin/redmine_issue_open_date#15]
Redmine 3.4.6.stable

Invoking from cron: 
rake issue_open_date:switch --silent RAILS_ENV="production" --trace

got this stacktrace
> ** Invoke issue_open_date:switch (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute issue_open_date:switch
> rake aborted!
> NameError: uninitialized constant IssueOpenWorker
> /home/redmine/plugins/redmine_issue_open_date/lib/tasks/issue_open_date.rake:3:in `block (2 levels) in <top (required)>'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `call'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
> /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
> /var/lib/gems/2.1.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:23:in `load'
> /usr/local/bin/rake:23:in `<main>'
> Tasks: TOP => issue_open_date:switch

tried develop branch but no luck

**Comment by funk-yourself** [comment]
Hello!
Please, try `fix-worker-autoload` branch
