### ISSUE TITLE
Не отображается календарик даты

### ISSUE THREAD

**Issue by miramir** [centosadmin/redmine_issue_open_date#2]
Заметил такую особенность, если перевести задачу в замороженное состояние (дату при этом можно не выставлять). То при следующем редактировании задачи, календарик рядом с полем "Открыть заново" не появляется.

**Comment by miramir** [comment]
никаких ошибок в консоли браузера при этом нет.

**Comment by olemskoi** [comment]
Пожалуйста, откройте задачу заново, если ошибка еще актуальна.
