### ISSUE TITLE
Нельзя зайти в настройки плагина

### ISSUE THREAD

**Issue by demiurg85** [centosadmin/redmine_issue_open_date#5]
После установки плагина первым делом снял все галочки с блока "Статус Заморожена" (чтобы текущие задачи не попали под действие этого плагина), после чего создал статус "Заморожена", но в настройки плагина уже система не пустила (Internal error), в том числе задачи перестали открываться с той же ошибкой. Пока пришлось плагин удалить.
После переустановки плагина проблема осталась. Как восстановить работоспособоность плагина?
Также вопрос:  есть ли возможность распространить действие плагина только на определенный проект?

Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_issue_open_date"}
  SQL (4.5ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2017-02-27 11:45:16' WHERE `tokens`.`user_id` = 4 AND `tokens`.`value` = 'cdeeaa69e7c3577ecf54a00ec787a31f1aff1ff6' AND `tokens`.`action` = 'session'
   (0.4ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 4 LIMIT 1
  Current user: aleksey.bogdanov (id=4)
  IssueStatus Load (0.4ms)  SELECT  `issue_statuses`.* FROM `issue_statuses`  ORDER BY `issue_statuses`.`id` ASC LIMIT 1000
  Rendered plugins/redmine_issue_open_date/app/views/settings/_issue_open_date.html.erb (8.2ms)
  Rendered settings/plugin.html.erb within layouts/admin (9.7ms)
Completed 500 Internal Server Error in 21ms (ActiveRecord: 5.7ms)

**Comment by olemskoi** [comment]
Здравствуйте!

Скорее всего вам нужно выполнить миграции плагинов.

> Также вопрос: есть ли возможность распространить действие плагина только на определенный проект?

Такая возможность не реализована.
